[package]
name = "worker-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.2"
http-body-util = "0.1"
hyper = { version = "1.5.1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
